### ISSUE TITLE
Documentar processo de criação do banco de dados

### ISSUE THREAD

**Issue by flavioamieiro** [AlertaDengue/AlertaDengueCaptura#17]
Enquanto eu estava tentando reproduzir um bug no ambiente de produção (o celery não parecia estar executando as tarefas) tentei executar o código na minha máquina e tive dificuldade na hora de criar o banco de dados. Existe um script em `dbschema/Banco_de_dados_do_Alerta_Dengue_create.sql`, mas executando ele com `psql < dbschema/Banco_de_dados_do_Alerta_Dengue_create.sql` eu tive um erro. Seria bom se no README esse processo estivesse documentado.

**Comment by fccoelho** [comment]
@flavioamieiro , eu tenho tentado manter o script atualizado, mas como fiz algumas alterações no banco em produção posso ter introduzido algum bug ao registrar as alterações no SQL que está no repo. Talvez a melhor maneira de corrigir seja gerando um dump só do schema a partir do servidor, sem os dados.

**Comment by fccoelho** [comment]
@flavioamieiro esta issue ainda está aberta?

**Comment by flavioamieiro** [comment]
@fccoelho acho que a questão aqui é um pouco mais complicada do que eu pensei quando criei essa issue.

O problema todo é que o banco surgiu "organicamente", com várias tabelas sendo criados em momentos diferentes e sem que isso estivesse muito bem documentado. No AlertaDengue/AlertaDengue nós tentamos manter todas as alterações que aquela aplicação fez no banco no diretório [sql](https://github.com/AlertaDengue/AlertaDengue/tree/master/sql), mas eu acho que não existe isso para todas as alterações que foram feitas no banco desde o início.

A solução que encontramos para esse problema foi criar os dumps do banco de produção para usarmos como ponto de partida na hora de debugar/desenvolver. Poderíamos criar um dump do banco sem os dados, só com a estrutura, e isso serviria como uma espécie de "migração inicial" para o banco. Mas, considerando a forma como várias aplicações são dependentes da existência de dados específicos em cada tabela, não acho que isso seja uma solução muito viável.

Acho que, se você concordar, podemos fechar essa issue por causa da existência dos dumps.

**Comment by fccoelho** [comment]
Ok podemos fechar.

Em 31 de out de 2017 17:20, "Flávio Amieiro" <notifications@github.com>
escreveu:
