### ISSUE TITLE
Redefinir a tabela Clima_Satelite

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengueCaptura#22]
Sugestão, para ficar uma tabela generica para todos os dados de satelite.

CREATE TABLE "Municipio"."Clima_Satelite"
(
  id bigserial NOT NULL,
  data date NOT NULL,
  "municipio_geocodigo" integer NOT NULL,
  "satelite", string NOT NULL, # info sobre a fonte do dado
  "nomevar" string NOT NULL,  # variavel coletada (tmin, tmax, enso, etc)
  "coordx" integer NOT NULL, 
  "coordy" integer NOT NULL,
  "valorvar" numeric(4,2) NOT NULL,  # valor mensurado
# nao sei essa parte:

  CONSTRAINT "Clima_Satelite_pk" PRIMARY KEY (id),
      REFERENCES "Municipio"."Localidade" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)

**Comment by fccoelho** [comment]
closing. Outdated
