### ISSUE TITLE
Script de verificação do upload precisa verificar datas

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengueCaptura#23]
@flavioamieiro: nos DBFs do ES a coluna DT_NOTIFIC tem várias datas com formatação errada. 
(só confirmei isso no dbf de 2015.)
O nosso validador de Upload vai ter que monitorar isso também. 
Estes registros com datas mal formatadas, estão "aparentemente" sendo ignorados pelo load SINAN, pois as contagens de casos para os municípios do ES estão muito baixas.

Acho que nosso validador de DBF vai ter que evoluir para uma espécie de sinan-lint.

**Comment by flavioamieiro** [comment]
O commit (https://github.com/AlertaDengue/AlertaDengue/commit/1d6e549396acf609ed2f6a51ca79153bcfbc633a)[1d6e54939] no AlertaDengue/AlertaDengue garante que o tipo declarado no campo da data de notificação (e outros campos que são de data) é 'D' (o tipo certo para data). Pelo que vi nos DBFs do ES, o problema era esse (as datas estavam vindo num campo do tipo 'C' - Char - e no format '20150101').

**Comment by flavioamieiro** [comment]
@fccoelho vou fechar essa issue já que [a validação inicial do dbf](https://github.com/AlertaDengue/AlertaDengue/blob/master/AlertaDengue/dbf/validation.py#L57-L60) já garante que os campos que representam datas estão declarados como o tipo data (e portanto são parseados pela biblioteca que lê o dbf).
