### ISSUE TITLE
Enable Postgis features no banco

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengueCaptura#27]
@flavioamieiro 
@xmnlab 

Vamos precisar habilitar a funcionalidade de postGIS no nosso banco para começar a poder populá-lo com dados das imagens de satélite. Isto parece um [procedimento](https://stackoverflow.com/questions/15049455/convert-a-normal-postgres-database-to-postgis-database) muito simples, mas seria bom que fosse bem documentado junto ao procedimento de deploy do projeto. @flavioamieiro onde estas regras estão sendo mantidas atualmente?

**Comment by flavioamieiro** [comment]
@fccoelho 

Por causa das questões que apontei na issue do [AlertaDengueCaptura](https://github.com/AlertaDengue/AlertaDengueCaptura/issues/17#issuecomment-340878541), a gente não tem exatamente uma documentação muito extensa do nosso banco. O que serve como base para a gente é sempre o banco de produção. 

Para o banco exclusivo dessa aplicação django, a documentação está toda nas migrações. Nós já tínhamos, inclusive, o postgis instalado no servidor por que o banco do django precisava dele antigamente. Isso está documentado no [dockerfile que controla a reprodução do banco no ambiente de staging](https://github.com/AlertaDengue/AlertaDengue/blob/develop/Dockerfile-postgres). Eu diria que essa é a documentação para a replicação do banco (mas ela ainda depende do dump do banco de produção, pelas razões que expliquei na [outra issue](https://github.com/AlertaDengue/AlertaDengueCaptura/issues/17#issuecomment-340878541)).

Eu criei a extensão no banco dengue e fiz um dump novo já incluindo essa extensão. Se novas tabelas forem criadas (ou tabelas anteriores forem alteradas), seria interessante criar um arquivo .sql dessas mudanças e incluí-lo nesse projeto, no diretório [`sql`](https://github.com/AlertaDengue/AlertaDengue/tree/master/sql).

**Comment by fccoelho** [comment]
Ok. Ainda não defini como vamos colocar os dados no banco.

Em 31 de out de 2017 17:33, "Flávio Amieiro" <notifications@github.com>
escreveu:

**Comment by flavioamieiro** [comment]
@fccoelho podemos fechar essa issue?

A extensão PostGIS já está habilitada no banco de produção.
