### ISSUE TITLE
Mover captura de imagens de satélites para este projeto

### ISSUE THREAD

**Issue by fccoelho** [AlertaDengue/AlertaDengueCaptura#30]
O @Dinidiniz já escreveu scrits para capturar automáticamente as imagens de que vamos precisar para o projeto diretamente a partir do Google Earth Engine, precisamos integrar este código ao projeto e definir uma periodicidade para a sua execução.

**Comment by flavioamieiro** [comment]
@Dinidiniz se você puder trazer pra um branch desse repositório o código, eu posso me encarregar de terminar a integração com o resto do código (inclusive a [questão do diretório onde guardaremos as imagens](https://github.com/AlertaDengue/AlertaDengue/issues/152#issuecomment-349440494)).

**Comment by Dinidiniz** [comment]
Olá @flavioamieiro, no caso prefere que eu de um fork no repositório e faça um branch para integrar?

https://github.com/Dinidiniz/GEEdownloader

O código no momento se encontra neste repositório aqui.

**Comment by flavioamieiro** [comment]
@Dinidiniz eu posso buscar desse repositório e trazer pra cá. Obrigado!

Eu provavelmente vou ter que extrair o código dos notebooks para scripts que vão rodar em outro contexto (provavelmente como tarefas do celery). Você pode, por favor, descrever quais são as imagens que precisamos e quais notebooks são responsáveis pela captura de cada uma delas? Assim eu posso entender melhor essa parte do projeto e partir para a integração do código.

**Comment by Dinidiniz** [comment]
> Você pode, por favor, descrever quais são as imagens que precisamos e quais notebooks são responsáveis pela captura de cada uma delas?

1. Temos que primeiramente dar autorização para uso de nosso email google nos códigos python: [Tutorial](https://developers.google.com/earth-engine/python_install_manual). 

2. Este arquivo tem as coordenadas do Brasil: [link](https://github.com/Dinidiniz/GEEdownloader/blob/master/BrasilCoordenadas.txt).  Também terá que baixar ele para o código funcionar.

3. Neste notebook: [link](https://github.com/Dinidiniz/GEEdownloader/blob/master/download%20maps.ipynb). há as funções para captura de cada satélite. Todas iremos usar.

4. Neste notebook: [link](https://github.com/Dinidiniz/GEEdownloader/blob/master/Drive%20downloader.ipynb), há rascunhos para um código de captura direto do google drive. Para isso temos que baixar também o arquivo 'client_secrets.json' dentro do [Painel de API's do google](https://console.developers.google.com/). Caso haja mais dúvidas dentro dessa parte, eu posso ajudar com mais detalhes: [Página de tutorial](https://developers.google.com/api-client-library/python/guide/aaa_client_secrets)

**Comment by flavioamieiro** [comment]
@Dinidiniz muito obrigado!

Isso já me dá uma ideia melhor de por onde começar. Se eu tiver alguma dúvida mais pontual eu aviso.
