### ISSUE TITLE
Incluir os municipios do MA, RS e SP nas capturas de tweet

### ISSUE THREAD

**Issue by claudia-codeco** [AlertaDengue/AlertaDengueCaptura#64]
**Problema**

A tabela tweet não tem os tweets para os municípios do Rio Grande do Sul , Maranhão e São Paulo.
Isso acontece porque eles não estão no arquivo municipios (aqui no AlertaDengueCaptura).

É preciso baixar os dados históricos e manter a captura semanal

**Solução imediata**
Acrescentar todos os municipios do MA no arquivo municipios
Acrescentar os municipios de SP: 3549805, 3506003 e 3552205 no arquivo municipios 
Acrescentar o municipio do RS: 4314902 no arquivo municipios  

**Solucao ideal**
Atualizar a lista de municipios via consulta à tabela notificacao

**Comment by fccoelho** [comment]
@esloch could you report on this issue? what is holding it back?

**Comment by esloch** [comment]
Hi @fccoelho , I was concluding the download_app PR ... I will be working on this issue and following up on the problem with the home charts, could it be?
